#############################################################################
# Makefile for building: dde-introduction
# Generated by qmake (3.1) (Qt 5.15.8)
# Project:  dde-introduction.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile dde-introduction.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_MESSAGELOGCONTEXT -DQT_WIDGETS_LIB -DQT_X11EXTRAS_LIB -DQT_GUI_LIB -DQT_CONCURRENT_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_NO_DEBUG -DQT_MULTIMEDIAWIDGETS_LIB -DQT_WIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_GUI_LIB -DQT_DBUS_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/include/dtk5/DWidget -I/usr/include/dtk5/DCore -I/usr/include/dtk5/DLog -I/usr/include/libdframeworkdbus-2.0 -I/usr/include/libgxmr -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = dde-introduction1.0.0
DISTDIR = /home/shenmo/Desktop/gxde-introduction/.tmp/dde-introduction1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath-link,/usr/lib/x86_64-linux-gnu
LIBS          = $(SUBLIBS) -ldframeworkdbus -lgxmr -lQt5Widgets -lQt5X11Extras -lQt5Gui -lQt5Concurrent -lQt5Network -lQt5Core -ldtkwidget -ldtkcore -ldtklog /usr/lib/x86_64-linux-gnu/libQt5MultimediaWidgets.so /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Multimedia.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5DBus.so /usr/lib/x86_64-linux-gnu/libQt5Network.so /usr/lib/x86_64-linux-gnu/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/basemodulewidget.cpp \
		src/main.cpp \
		src/mainwindow.cpp \
		src/model.cpp \
		src/normalwindow.cpp \
		src/worker.cpp \
		src/modules/about.cpp \
		src/modules/desktopmodemodule.cpp \
		src/modules/iconmodule.cpp \
		src/modules/moduleinterface.cpp \
		src/modules/normalmodule.cpp \
		src/modules/support.cpp \
		src/modules/videowidget.cpp \
		src/modules/wmmodemodule.cpp \
		src/widgets/basewidget.cpp \
		src/widgets/borderwidget.cpp \
		src/widgets/bottomnavigation.cpp \
		src/widgets/navigationbutton.cpp \
		src/widgets/nextbutton.cpp \
		src/dvideowidget.cpp \
		src/modules/photoslide.cpp qrc_dde-introduction.cpp \
		moc_basemodulewidget.cpp \
		moc_mainwindow.cpp \
		moc_model.cpp \
		moc_normalwindow.cpp \
		moc_worker.cpp \
		moc_about.cpp \
		moc_desktopmodemodule.cpp \
		moc_iconmodule.cpp \
		moc_moduleinterface.cpp \
		moc_normalmodule.cpp \
		moc_support.cpp \
		moc_videowidget.cpp \
		moc_wmmodemodule.cpp \
		moc_basewidget.cpp \
		moc_borderwidget.cpp \
		moc_bottomnavigation.cpp \
		moc_navigationbutton.cpp \
		moc_nextbutton.cpp \
		moc_dvideowidget.cpp \
		moc_photoslide.cpp
OBJECTS       = basemodulewidget.o \
		main.o \
		mainwindow.o \
		model.o \
		normalwindow.o \
		worker.o \
		about.o \
		desktopmodemodule.o \
		iconmodule.o \
		moduleinterface.o \
		normalmodule.o \
		support.o \
		videowidget.o \
		wmmodemodule.o \
		basewidget.o \
		borderwidget.o \
		bottomnavigation.o \
		navigationbutton.o \
		nextbutton.o \
		dvideowidget.o \
		photoslide.o \
		qrc_dde-introduction.o \
		moc_basemodulewidget.o \
		moc_mainwindow.o \
		moc_model.o \
		moc_normalwindow.o \
		moc_worker.o \
		moc_about.o \
		moc_desktopmodemodule.o \
		moc_iconmodule.o \
		moc_moduleinterface.o \
		moc_normalmodule.o \
		moc_support.o \
		moc_videowidget.o \
		moc_wmmodemodule.o \
		moc_basewidget.o \
		moc_borderwidget.o \
		moc_bottomnavigation.o \
		moc_navigationbutton.o \
		moc_nextbutton.o \
		moc_dvideowidget.o \
		moc_photoslide.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCodecs.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KConfigCore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KConfigGui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCoreAddons.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KWindowSystem.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dtkcore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dtkgui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dtklog.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dtkwidget.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dtkwm.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webengine.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/link_pkgconfig.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dbuscommon.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dbusinterfaces.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dbusadaptors.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		dde-introduction.pro src/basemodulewidget.h \
		src/mainwindow.h \
		src/model.h \
		src/normalwindow.h \
		src/worker.h \
		src/modules/about.h \
		src/modules/desktopmodemodule.h \
		src/modules/iconmodule.h \
		src/modules/moduleinterface.h \
		src/modules/normalmodule.h \
		src/modules/support.h \
		src/modules/videowidget.h \
		src/modules/wmmodemodule.h \
		src/widgets/basewidget.h \
		src/widgets/borderwidget.h \
		src/widgets/bottomnavigation.h \
		src/widgets/navigationbutton.h \
		src/widgets/nextbutton.h \
		src/dvideowidget.h \
		src/modules/photoslide.h src/basemodulewidget.cpp \
		src/main.cpp \
		src/mainwindow.cpp \
		src/model.cpp \
		src/normalwindow.cpp \
		src/worker.cpp \
		src/modules/about.cpp \
		src/modules/desktopmodemodule.cpp \
		src/modules/iconmodule.cpp \
		src/modules/moduleinterface.cpp \
		src/modules/normalmodule.cpp \
		src/modules/support.cpp \
		src/modules/videowidget.cpp \
		src/modules/wmmodemodule.cpp \
		src/widgets/basewidget.cpp \
		src/widgets/borderwidget.cpp \
		src/widgets/bottomnavigation.cpp \
		src/widgets/navigationbutton.cpp \
		src/widgets/nextbutton.cpp \
		src/dvideowidget.cpp \
		src/modules/photoslide.cpp
QMAKE_TARGET  = dde-introduction
DESTDIR       = 
TARGET        = dde-introduction


first: all
####### Build rules

dde-introduction:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: dde-introduction.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCodecs.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KConfigCore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KConfigGui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCoreAddons.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KWindowSystem.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dtkcore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dtkgui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dtklog.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dtkwidget.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dtkwm.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webengine.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/link_pkgconfig.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dbuscommon.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dbusinterfaces.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dbusadaptors.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		dde-introduction.pro \
		dde-introduction.qrc \
		/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5X11Extras.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Concurrent.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Network.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) -o Makefile dde-introduction.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCodecs.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KConfigCore.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KConfigGui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCoreAddons.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KWindowSystem.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dtkcore.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dtkgui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dtklog.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dtkwidget.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dtkwm.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioning.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioningquick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webchannel.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webengine.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_websockets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_x11extras.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/link_pkgconfig.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dbuscommon.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dbusinterfaces.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dbusadaptors.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
dde-introduction.pro:
dde-introduction.qrc:
/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt5X11Extras.prl:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Concurrent.prl:
/usr/lib/x86_64-linux-gnu/libQt5Network.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile dde-introduction.pro

qmake_all: FORCE


all: Makefile dde-introduction

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents dde-introduction.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/basemodulewidget.h src/mainwindow.h src/model.h src/normalwindow.h src/worker.h src/modules/about.h src/modules/desktopmodemodule.h src/modules/iconmodule.h src/modules/moduleinterface.h src/modules/normalmodule.h src/modules/support.h src/modules/videowidget.h src/modules/wmmodemodule.h src/widgets/basewidget.h src/widgets/borderwidget.h src/widgets/bottomnavigation.h src/widgets/navigationbutton.h src/widgets/nextbutton.h src/dvideowidget.h src/modules/photoslide.h $(DISTDIR)/
	$(COPY_FILE) --parents src/basemodulewidget.cpp src/main.cpp src/mainwindow.cpp src/model.cpp src/normalwindow.cpp src/worker.cpp src/modules/about.cpp src/modules/desktopmodemodule.cpp src/modules/iconmodule.cpp src/modules/moduleinterface.cpp src/modules/normalmodule.cpp src/modules/support.cpp src/modules/videowidget.cpp src/modules/wmmodemodule.cpp src/widgets/basewidget.cpp src/widgets/borderwidget.cpp src/widgets/bottomnavigation.cpp src/widgets/navigationbutton.cpp src/widgets/nextbutton.cpp src/dvideowidget.cpp src/modules/photoslide.cpp $(DISTDIR)/
	$(COPY_FILE) --parents translations/dde-introduction.ts $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_dde-introduction.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_dde-introduction.cpp
qrc_dde-introduction.cpp: dde-introduction.qrc \
		/usr/lib/qt5/bin/rcc \
		resources/3d_big.png \
		resources/previous_disabled.svg \
		resources/pause_hover.svg \
		resources/close_round_hover.svg \
		resources/play_press.svg \
		resources/Twitter.svg \
		resources/Facebook.svg \
		resources/3d_big@2x.png \
		resources/effective_mode_big.png \
		resources/dde-introduction.svg \
		resources/QQ.svg \
		resources/2d_big.png \
		resources/config.json \
		resources/previous_normal.svg \
		resources/weibo.svg \
		resources/previous_hover.svg \
		resources/discord-logo-blue.svg \
		resources/fashion_mode_small.png \
		resources/close_round_normal.svg \
		resources/list_select@2x.png \
		resources/3d_small.png \
		resources/pause_normal.svg \
		resources/Mail.svg \
		resources/list_select.png \
		resources/2d_big@2x.png \
		resources/3d_small@2x.png \
		resources/fashion_mode_big.png \
		resources/previous_press.svg \
		resources/fashion_mode_big@2x.png \
		resources/play_normal.svg \
		resources/2d_small.png \
		resources/effective_mode_big@2x.png \
		resources/effective_mode_small.png \
		resources/pause_press.svg \
		resources/close_round_press.svg \
		resources/fashion_mode_small@2x.png \
		resources/effective_mode_small@2x.png \
		resources/2d_small@2x.png \
		resources/play_hover.svg \
		resources/slide_small/04.jpg \
		resources/slide_small/03.jpg \
		resources/slide_small/07.jpg \
		resources/slide_small/02.jpg \
		resources/slide_small/06.jpg \
		resources/slide_small/01.jpg \
		resources/slide_small/05.jpg \
		resources/slide_big/04.jpg \
		resources/slide_big/03.jpg \
		resources/slide_big/07.jpg \
		resources/slide_big/02.jpg \
		resources/slide_big/06.jpg \
		resources/slide_big/01.jpg \
		resources/slide_big/05.jpg
	/usr/lib/qt5/bin/rcc -name dde-introduction dde-introduction.qrc -o qrc_dde-introduction.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -std=gnu++11 -Wall -Wextra -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_basemodulewidget.cpp moc_mainwindow.cpp moc_model.cpp moc_normalwindow.cpp moc_worker.cpp moc_about.cpp moc_desktopmodemodule.cpp moc_iconmodule.cpp moc_moduleinterface.cpp moc_normalmodule.cpp moc_support.cpp moc_videowidget.cpp moc_wmmodemodule.cpp moc_basewidget.cpp moc_borderwidget.cpp moc_bottomnavigation.cpp moc_navigationbutton.cpp moc_nextbutton.cpp moc_dvideowidget.cpp moc_photoslide.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_basemodulewidget.cpp moc_mainwindow.cpp moc_model.cpp moc_normalwindow.cpp moc_worker.cpp moc_about.cpp moc_desktopmodemodule.cpp moc_iconmodule.cpp moc_moduleinterface.cpp moc_normalmodule.cpp moc_support.cpp moc_videowidget.cpp moc_wmmodemodule.cpp moc_basewidget.cpp moc_borderwidget.cpp moc_bottomnavigation.cpp moc_navigationbutton.cpp moc_nextbutton.cpp moc_dvideowidget.cpp moc_photoslide.cpp
moc_basemodulewidget.cpp: src/basemodulewidget.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/shenmo/Desktop/gxde-introduction/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/shenmo/Desktop/gxde-introduction -I/usr/include/dtk5/DWidget -I/usr/include/dtk5/DCore -I/usr/include/dtk5/DLog -I/usr/include/libdframeworkdbus-2.0 -I/usr/include/libgxmr -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/basemodulewidget.h -o moc_basemodulewidget.cpp

moc_mainwindow.cpp: src/mainwindow.h \
		src/widgets/nextbutton.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/shenmo/Desktop/gxde-introduction/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/shenmo/Desktop/gxde-introduction -I/usr/include/dtk5/DWidget -I/usr/include/dtk5/DCore -I/usr/include/dtk5/DLog -I/usr/include/libdframeworkdbus-2.0 -I/usr/include/libgxmr -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/mainwindow.h -o moc_mainwindow.cpp

moc_model.cpp: src/model.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/shenmo/Desktop/gxde-introduction/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/shenmo/Desktop/gxde-introduction -I/usr/include/dtk5/DWidget -I/usr/include/dtk5/DCore -I/usr/include/dtk5/DLog -I/usr/include/libdframeworkdbus-2.0 -I/usr/include/libgxmr -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/model.h -o moc_model.cpp

moc_normalwindow.cpp: src/normalwindow.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/shenmo/Desktop/gxde-introduction/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/shenmo/Desktop/gxde-introduction -I/usr/include/dtk5/DWidget -I/usr/include/dtk5/DCore -I/usr/include/dtk5/DLog -I/usr/include/libdframeworkdbus-2.0 -I/usr/include/libgxmr -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/normalwindow.h -o moc_normalwindow.cpp

moc_worker.cpp: src/worker.h \
		src/model.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/shenmo/Desktop/gxde-introduction/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/shenmo/Desktop/gxde-introduction -I/usr/include/dtk5/DWidget -I/usr/include/dtk5/DCore -I/usr/include/dtk5/DLog -I/usr/include/libdframeworkdbus-2.0 -I/usr/include/libgxmr -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/worker.h -o moc_worker.cpp

moc_about.cpp: src/modules/about.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/shenmo/Desktop/gxde-introduction/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/shenmo/Desktop/gxde-introduction -I/usr/include/dtk5/DWidget -I/usr/include/dtk5/DCore -I/usr/include/dtk5/DLog -I/usr/include/libdframeworkdbus-2.0 -I/usr/include/libgxmr -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/modules/about.h -o moc_about.cpp

moc_desktopmodemodule.cpp: src/modules/desktopmodemodule.h \
		src/modules/moduleinterface.h \
		src/model.h \
		src/worker.h \
		src/widgets/basewidget.h \
		src/widgets/borderwidget.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/shenmo/Desktop/gxde-introduction/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/shenmo/Desktop/gxde-introduction -I/usr/include/dtk5/DWidget -I/usr/include/dtk5/DCore -I/usr/include/dtk5/DLog -I/usr/include/libdframeworkdbus-2.0 -I/usr/include/libgxmr -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/modules/desktopmodemodule.h -o moc_desktopmodemodule.cpp

moc_iconmodule.cpp: src/modules/iconmodule.h \
		src/modules/moduleinterface.h \
		src/model.h \
		src/worker.h \
		src/widgets/basewidget.h \
		src/widgets/borderwidget.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/shenmo/Desktop/gxde-introduction/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/shenmo/Desktop/gxde-introduction -I/usr/include/dtk5/DWidget -I/usr/include/dtk5/DCore -I/usr/include/dtk5/DLog -I/usr/include/libdframeworkdbus-2.0 -I/usr/include/libgxmr -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/modules/iconmodule.h -o moc_iconmodule.cpp

moc_moduleinterface.cpp: src/modules/moduleinterface.h \
		src/model.h \
		src/worker.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/shenmo/Desktop/gxde-introduction/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/shenmo/Desktop/gxde-introduction -I/usr/include/dtk5/DWidget -I/usr/include/dtk5/DCore -I/usr/include/dtk5/DLog -I/usr/include/libdframeworkdbus-2.0 -I/usr/include/libgxmr -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/modules/moduleinterface.h -o moc_moduleinterface.cpp

moc_normalmodule.cpp: src/modules/normalmodule.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/shenmo/Desktop/gxde-introduction/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/shenmo/Desktop/gxde-introduction -I/usr/include/dtk5/DWidget -I/usr/include/dtk5/DCore -I/usr/include/dtk5/DLog -I/usr/include/libdframeworkdbus-2.0 -I/usr/include/libgxmr -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/modules/normalmodule.h -o moc_normalmodule.cpp

moc_support.cpp: src/modules/support.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/shenmo/Desktop/gxde-introduction/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/shenmo/Desktop/gxde-introduction -I/usr/include/dtk5/DWidget -I/usr/include/dtk5/DCore -I/usr/include/dtk5/DLog -I/usr/include/libdframeworkdbus-2.0 -I/usr/include/libgxmr -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/modules/support.h -o moc_support.cpp

moc_videowidget.cpp: src/modules/videowidget.h \
		src/modules/moduleinterface.h \
		src/model.h \
		src/worker.h \
		src/dvideowidget.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/shenmo/Desktop/gxde-introduction/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/shenmo/Desktop/gxde-introduction -I/usr/include/dtk5/DWidget -I/usr/include/dtk5/DCore -I/usr/include/dtk5/DLog -I/usr/include/libdframeworkdbus-2.0 -I/usr/include/libgxmr -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/modules/videowidget.h -o moc_videowidget.cpp

moc_wmmodemodule.cpp: src/modules/wmmodemodule.h \
		src/modules/moduleinterface.h \
		src/model.h \
		src/worker.h \
		src/widgets/basewidget.h \
		src/widgets/borderwidget.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/shenmo/Desktop/gxde-introduction/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/shenmo/Desktop/gxde-introduction -I/usr/include/dtk5/DWidget -I/usr/include/dtk5/DCore -I/usr/include/dtk5/DLog -I/usr/include/libdframeworkdbus-2.0 -I/usr/include/libgxmr -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/modules/wmmodemodule.h -o moc_wmmodemodule.cpp

moc_basewidget.cpp: src/widgets/basewidget.h \
		src/widgets/borderwidget.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/shenmo/Desktop/gxde-introduction/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/shenmo/Desktop/gxde-introduction -I/usr/include/dtk5/DWidget -I/usr/include/dtk5/DCore -I/usr/include/dtk5/DLog -I/usr/include/libdframeworkdbus-2.0 -I/usr/include/libgxmr -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/widgets/basewidget.h -o moc_basewidget.cpp

moc_borderwidget.cpp: src/widgets/borderwidget.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/shenmo/Desktop/gxde-introduction/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/shenmo/Desktop/gxde-introduction -I/usr/include/dtk5/DWidget -I/usr/include/dtk5/DCore -I/usr/include/dtk5/DLog -I/usr/include/libdframeworkdbus-2.0 -I/usr/include/libgxmr -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/widgets/borderwidget.h -o moc_borderwidget.cpp

moc_bottomnavigation.cpp: src/widgets/bottomnavigation.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/shenmo/Desktop/gxde-introduction/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/shenmo/Desktop/gxde-introduction -I/usr/include/dtk5/DWidget -I/usr/include/dtk5/DCore -I/usr/include/dtk5/DLog -I/usr/include/libdframeworkdbus-2.0 -I/usr/include/libgxmr -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/widgets/bottomnavigation.h -o moc_bottomnavigation.cpp

moc_navigationbutton.cpp: src/widgets/navigationbutton.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/shenmo/Desktop/gxde-introduction/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/shenmo/Desktop/gxde-introduction -I/usr/include/dtk5/DWidget -I/usr/include/dtk5/DCore -I/usr/include/dtk5/DLog -I/usr/include/libdframeworkdbus-2.0 -I/usr/include/libgxmr -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/widgets/navigationbutton.h -o moc_navigationbutton.cpp

moc_nextbutton.cpp: src/widgets/nextbutton.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/shenmo/Desktop/gxde-introduction/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/shenmo/Desktop/gxde-introduction -I/usr/include/dtk5/DWidget -I/usr/include/dtk5/DCore -I/usr/include/dtk5/DLog -I/usr/include/libdframeworkdbus-2.0 -I/usr/include/libgxmr -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/widgets/nextbutton.h -o moc_nextbutton.cpp

moc_dvideowidget.cpp: src/dvideowidget.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/shenmo/Desktop/gxde-introduction/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/shenmo/Desktop/gxde-introduction -I/usr/include/dtk5/DWidget -I/usr/include/dtk5/DCore -I/usr/include/dtk5/DLog -I/usr/include/libdframeworkdbus-2.0 -I/usr/include/libgxmr -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/dvideowidget.h -o moc_dvideowidget.cpp

moc_photoslide.cpp: src/modules/photoslide.h \
		src/modules/moduleinterface.h \
		src/model.h \
		src/worker.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/shenmo/Desktop/gxde-introduction/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/shenmo/Desktop/gxde-introduction -I/usr/include/dtk5/DWidget -I/usr/include/dtk5/DCore -I/usr/include/dtk5/DLog -I/usr/include/libdframeworkdbus-2.0 -I/usr/include/libgxmr -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/modules/photoslide.h -o moc_photoslide.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all: dvideowidget.moc
compiler_moc_source_clean:
	-$(DEL_FILE) dvideowidget.moc
dvideowidget.moc: src/dvideowidget.cpp \
		src/dvideowidget.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/shenmo/Desktop/gxde-introduction/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/shenmo/Desktop/gxde-introduction -I/usr/include/dtk5/DWidget -I/usr/include/dtk5/DCore -I/usr/include/dtk5/DLog -I/usr/include/libdframeworkdbus-2.0 -I/usr/include/libgxmr -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/dvideowidget.cpp -o dvideowidget.moc

compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_moc_source_clean 

####### Compile

basemodulewidget.o: src/basemodulewidget.cpp src/basemodulewidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o basemodulewidget.o src/basemodulewidget.cpp

main.o: src/main.cpp src/mainwindow.h \
		src/widgets/nextbutton.h \
		src/normalwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

mainwindow.o: src/mainwindow.cpp src/mainwindow.h \
		src/widgets/nextbutton.h \
		src/modules/desktopmodemodule.h \
		src/modules/moduleinterface.h \
		src/model.h \
		src/worker.h \
		src/widgets/basewidget.h \
		src/widgets/borderwidget.h \
		src/modules/wmmodemodule.h \
		src/modules/iconmodule.h \
		src/modules/normalmodule.h \
		src/modules/photoslide.h \
		src/basemodulewidget.h \
		src/modules/videowidget.h \
		src/dvideowidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o src/mainwindow.cpp

model.o: src/model.cpp src/model.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o model.o src/model.cpp

normalwindow.o: src/normalwindow.cpp src/normalwindow.h \
		src/modules/desktopmodemodule.h \
		src/modules/moduleinterface.h \
		src/model.h \
		src/worker.h \
		src/widgets/basewidget.h \
		src/widgets/borderwidget.h \
		src/modules/wmmodemodule.h \
		src/modules/iconmodule.h \
		src/basemodulewidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o normalwindow.o src/normalwindow.cpp

worker.o: src/worker.cpp src/worker.h \
		src/model.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o worker.o src/worker.cpp

about.o: src/modules/about.cpp src/modules/about.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o about.o src/modules/about.cpp

desktopmodemodule.o: src/modules/desktopmodemodule.cpp src/modules/desktopmodemodule.h \
		src/modules/moduleinterface.h \
		src/model.h \
		src/worker.h \
		src/widgets/basewidget.h \
		src/widgets/borderwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o desktopmodemodule.o src/modules/desktopmodemodule.cpp

iconmodule.o: src/modules/iconmodule.cpp src/modules/iconmodule.h \
		src/modules/moduleinterface.h \
		src/model.h \
		src/worker.h \
		src/widgets/basewidget.h \
		src/widgets/borderwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o iconmodule.o src/modules/iconmodule.cpp

moduleinterface.o: src/modules/moduleinterface.cpp src/modules/moduleinterface.h \
		src/model.h \
		src/worker.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moduleinterface.o src/modules/moduleinterface.cpp

normalmodule.o: src/modules/normalmodule.cpp src/modules/normalmodule.h \
		src/widgets/navigationbutton.h \
		src/modules/desktopmodemodule.h \
		src/modules/moduleinterface.h \
		src/model.h \
		src/worker.h \
		src/widgets/basewidget.h \
		src/widgets/borderwidget.h \
		src/modules/iconmodule.h \
		src/modules/wmmodemodule.h \
		src/modules/support.h \
		src/modules/about.h \
		src/modules/photoslide.h \
		src/widgets/bottomnavigation.h \
		src/modules/videowidget.h \
		src/dvideowidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o normalmodule.o src/modules/normalmodule.cpp

support.o: src/modules/support.cpp src/modules/support.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o support.o src/modules/support.cpp

videowidget.o: src/modules/videowidget.cpp src/modules/videowidget.h \
		src/modules/moduleinterface.h \
		src/model.h \
		src/worker.h \
		src/dvideowidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o videowidget.o src/modules/videowidget.cpp

wmmodemodule.o: src/modules/wmmodemodule.cpp src/modules/wmmodemodule.h \
		src/modules/moduleinterface.h \
		src/model.h \
		src/worker.h \
		src/widgets/basewidget.h \
		src/widgets/borderwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o wmmodemodule.o src/modules/wmmodemodule.cpp

basewidget.o: src/widgets/basewidget.cpp src/widgets/basewidget.h \
		src/widgets/borderwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o basewidget.o src/widgets/basewidget.cpp

borderwidget.o: src/widgets/borderwidget.cpp src/widgets/borderwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o borderwidget.o src/widgets/borderwidget.cpp

bottomnavigation.o: src/widgets/bottomnavigation.cpp src/widgets/bottomnavigation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bottomnavigation.o src/widgets/bottomnavigation.cpp

navigationbutton.o: src/widgets/navigationbutton.cpp src/widgets/navigationbutton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o navigationbutton.o src/widgets/navigationbutton.cpp

nextbutton.o: src/widgets/nextbutton.cpp src/widgets/nextbutton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o nextbutton.o src/widgets/nextbutton.cpp

dvideowidget.o: src/dvideowidget.cpp src/dvideowidget.h \
		dvideowidget.moc
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dvideowidget.o src/dvideowidget.cpp

photoslide.o: src/modules/photoslide.cpp src/modules/photoslide.h \
		src/modules/moduleinterface.h \
		src/model.h \
		src/worker.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o photoslide.o src/modules/photoslide.cpp

qrc_dde-introduction.o: qrc_dde-introduction.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_dde-introduction.o qrc_dde-introduction.cpp

moc_basemodulewidget.o: moc_basemodulewidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_basemodulewidget.o moc_basemodulewidget.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_model.o: moc_model.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_model.o moc_model.cpp

moc_normalwindow.o: moc_normalwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_normalwindow.o moc_normalwindow.cpp

moc_worker.o: moc_worker.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_worker.o moc_worker.cpp

moc_about.o: moc_about.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_about.o moc_about.cpp

moc_desktopmodemodule.o: moc_desktopmodemodule.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_desktopmodemodule.o moc_desktopmodemodule.cpp

moc_iconmodule.o: moc_iconmodule.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_iconmodule.o moc_iconmodule.cpp

moc_moduleinterface.o: moc_moduleinterface.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_moduleinterface.o moc_moduleinterface.cpp

moc_normalmodule.o: moc_normalmodule.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_normalmodule.o moc_normalmodule.cpp

moc_support.o: moc_support.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_support.o moc_support.cpp

moc_videowidget.o: moc_videowidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_videowidget.o moc_videowidget.cpp

moc_wmmodemodule.o: moc_wmmodemodule.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_wmmodemodule.o moc_wmmodemodule.cpp

moc_basewidget.o: moc_basewidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_basewidget.o moc_basewidget.cpp

moc_borderwidget.o: moc_borderwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_borderwidget.o moc_borderwidget.cpp

moc_bottomnavigation.o: moc_bottomnavigation.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_bottomnavigation.o moc_bottomnavigation.cpp

moc_navigationbutton.o: moc_navigationbutton.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_navigationbutton.o moc_navigationbutton.cpp

moc_nextbutton.o: moc_nextbutton.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_nextbutton.o moc_nextbutton.cpp

moc_dvideowidget.o: moc_dvideowidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dvideowidget.o moc_dvideowidget.cpp

moc_photoslide.o: moc_photoslide.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_photoslide.o moc_photoslide.cpp

####### Install

install_desktop: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/applications/ || mkdir -p $(INSTALL_ROOT)/usr/share/applications/
	$(QINSTALL) /home/shenmo/Desktop/gxde-introduction/dde-introduction.desktop $(INSTALL_ROOT)/usr/share/applications/dde-introduction.desktop

uninstall_desktop: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/applications/dde-introduction.desktop
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/applications/ 


install_target: first FORCE
	@test -d $(INSTALL_ROOT)/usr/bin/ || mkdir -p $(INSTALL_ROOT)/usr/bin/
	$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/bin/ 


install_icon: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/icons/hicolor/scalable/apps || mkdir -p $(INSTALL_ROOT)/usr/share/icons/hicolor/scalable/apps
	$(QINSTALL) /home/shenmo/Desktop/gxde-introduction/resources/dde-introduction.svg $(INSTALL_ROOT)/usr/share/icons/hicolor/scalable/apps/dde-introduction.svg

uninstall_icon: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/icons/hicolor/scalable/apps/dde-introduction.svg
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/icons/hicolor/scalable/apps/ 


install_qm_files: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/dde-introduction/translations/ || mkdir -p $(INSTALL_ROOT)/usr/share/dde-introduction/translations/
	$(QINSTALL) /home/shenmo/Desktop/gxde-introduction/translations/dde-introduction.qm $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction.qm
	$(QINSTALL) /home/shenmo/Desktop/gxde-introduction/translations/dde-introduction_af.qm $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_af.qm
	$(QINSTALL) /home/shenmo/Desktop/gxde-introduction/translations/dde-introduction_am_ET.qm $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_am_ET.qm
	$(QINSTALL) /home/shenmo/Desktop/gxde-introduction/translations/dde-introduction_ar.qm $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_ar.qm
	$(QINSTALL) /home/shenmo/Desktop/gxde-introduction/translations/dde-introduction_ast.qm $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_ast.qm
	$(QINSTALL) /home/shenmo/Desktop/gxde-introduction/translations/dde-introduction_az.qm $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_az.qm
	$(QINSTALL) /home/shenmo/Desktop/gxde-introduction/translations/dde-introduction_bg.qm $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_bg.qm
	$(QINSTALL) /home/shenmo/Desktop/gxde-introduction/translations/dde-introduction_bn.qm $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_bn.qm
	$(QINSTALL) /home/shenmo/Desktop/gxde-introduction/translations/dde-introduction_ca.qm $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_ca.qm
	$(QINSTALL) /home/shenmo/Desktop/gxde-introduction/translations/dde-introduction_cs.qm $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_cs.qm
	$(QINSTALL) /home/shenmo/Desktop/gxde-introduction/translations/dde-introduction_da.qm $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_da.qm
	$(QINSTALL) /home/shenmo/Desktop/gxde-introduction/translations/dde-introduction_de.qm $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_de.qm
	$(QINSTALL) /home/shenmo/Desktop/gxde-introduction/translations/dde-introduction_el.qm $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_el.qm
	$(QINSTALL) /home/shenmo/Desktop/gxde-introduction/translations/dde-introduction_en_AU.qm $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_en_AU.qm
	$(QINSTALL) /home/shenmo/Desktop/gxde-introduction/translations/dde-introduction_en_GB.qm $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_en_GB.qm
	$(QINSTALL) /home/shenmo/Desktop/gxde-introduction/translations/dde-introduction_eo.qm $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_eo.qm
	$(QINSTALL) /home/shenmo/Desktop/gxde-introduction/translations/dde-introduction_es.qm $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_es.qm
	$(QINSTALL) /home/shenmo/Desktop/gxde-introduction/translations/dde-introduction_es_419.qm $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_es_419.qm
	$(QINSTALL) /home/shenmo/Desktop/gxde-introduction/translations/dde-introduction_fa.qm $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_fa.qm
	$(QINSTALL) /home/shenmo/Desktop/gxde-introduction/translations/dde-introduction_fi.qm $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_fi.qm
	$(QINSTALL) /home/shenmo/Desktop/gxde-introduction/translations/dde-introduction_fil.qm $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_fil.qm
	$(QINSTALL) /home/shenmo/Desktop/gxde-introduction/translations/dde-introduction_fr.qm $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_fr.qm
	$(QINSTALL) /home/shenmo/Desktop/gxde-introduction/translations/dde-introduction_gl.qm $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_gl.qm
	$(QINSTALL) /home/shenmo/Desktop/gxde-introduction/translations/dde-introduction_gl_ES.qm $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_gl_ES.qm
	$(QINSTALL) /home/shenmo/Desktop/gxde-introduction/translations/dde-introduction_he.qm $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_he.qm
	$(QINSTALL) /home/shenmo/Desktop/gxde-introduction/translations/dde-introduction_hi_IN.qm $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_hi_IN.qm
	$(QINSTALL) /home/shenmo/Desktop/gxde-introduction/translations/dde-introduction_hr.qm $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_hr.qm
	$(QINSTALL) /home/shenmo/Desktop/gxde-introduction/translations/dde-introduction_hu.qm $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_hu.qm
	$(QINSTALL) /home/shenmo/Desktop/gxde-introduction/translations/dde-introduction_hy.qm $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_hy.qm
	$(QINSTALL) /home/shenmo/Desktop/gxde-introduction/translations/dde-introduction_id.qm $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_id.qm
	$(QINSTALL) /home/shenmo/Desktop/gxde-introduction/translations/dde-introduction_it.qm $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_it.qm
	$(QINSTALL) /home/shenmo/Desktop/gxde-introduction/translations/dde-introduction_ja.qm $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_ja.qm
	$(QINSTALL) /home/shenmo/Desktop/gxde-introduction/translations/dde-introduction_kn_IN.qm $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_kn_IN.qm
	$(QINSTALL) /home/shenmo/Desktop/gxde-introduction/translations/dde-introduction_ko.qm $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_ko.qm
	$(QINSTALL) /home/shenmo/Desktop/gxde-introduction/translations/dde-introduction_ku_IQ.qm $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_ku_IQ.qm
	$(QINSTALL) /home/shenmo/Desktop/gxde-introduction/translations/dde-introduction_lo.qm $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_lo.qm
	$(QINSTALL) /home/shenmo/Desktop/gxde-introduction/translations/dde-introduction_lt.qm $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_lt.qm
	$(QINSTALL) /home/shenmo/Desktop/gxde-introduction/translations/dde-introduction_ml.qm $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_ml.qm
	$(QINSTALL) /home/shenmo/Desktop/gxde-introduction/translations/dde-introduction_mn.qm $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_mn.qm
	$(QINSTALL) /home/shenmo/Desktop/gxde-introduction/translations/dde-introduction_ms.qm $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_ms.qm
	$(QINSTALL) /home/shenmo/Desktop/gxde-introduction/translations/dde-introduction_nb.qm $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_nb.qm
	$(QINSTALL) /home/shenmo/Desktop/gxde-introduction/translations/dde-introduction_ne.qm $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_ne.qm
	$(QINSTALL) /home/shenmo/Desktop/gxde-introduction/translations/dde-introduction_nl.qm $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_nl.qm
	$(QINSTALL) /home/shenmo/Desktop/gxde-introduction/translations/dde-introduction_pa.qm $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_pa.qm
	$(QINSTALL) /home/shenmo/Desktop/gxde-introduction/translations/dde-introduction_pl.qm $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_pl.qm
	$(QINSTALL) /home/shenmo/Desktop/gxde-introduction/translations/dde-introduction_pt.qm $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_pt.qm
	$(QINSTALL) /home/shenmo/Desktop/gxde-introduction/translations/dde-introduction_pt_BR.qm $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_pt_BR.qm
	$(QINSTALL) /home/shenmo/Desktop/gxde-introduction/translations/dde-introduction_ro.qm $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_ro.qm
	$(QINSTALL) /home/shenmo/Desktop/gxde-introduction/translations/dde-introduction_ru.qm $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_ru.qm
	$(QINSTALL) /home/shenmo/Desktop/gxde-introduction/translations/dde-introduction_sk.qm $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_sk.qm
	$(QINSTALL) /home/shenmo/Desktop/gxde-introduction/translations/dde-introduction_sl.qm $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_sl.qm
	$(QINSTALL) /home/shenmo/Desktop/gxde-introduction/translations/dde-introduction_sq.qm $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_sq.qm
	$(QINSTALL) /home/shenmo/Desktop/gxde-introduction/translations/dde-introduction_sr.qm $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_sr.qm
	$(QINSTALL) /home/shenmo/Desktop/gxde-introduction/translations/dde-introduction_sv.qm $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_sv.qm
	$(QINSTALL) /home/shenmo/Desktop/gxde-introduction/translations/dde-introduction_sw.qm $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_sw.qm
	$(QINSTALL) /home/shenmo/Desktop/gxde-introduction/translations/dde-introduction_ta.qm $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_ta.qm
	$(QINSTALL) /home/shenmo/Desktop/gxde-introduction/translations/dde-introduction_tr.qm $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_tr.qm
	$(QINSTALL) /home/shenmo/Desktop/gxde-introduction/translations/dde-introduction_ug.qm $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_ug.qm
	$(QINSTALL) /home/shenmo/Desktop/gxde-introduction/translations/dde-introduction_uk.qm $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_uk.qm
	$(QINSTALL) /home/shenmo/Desktop/gxde-introduction/translations/dde-introduction_vi.qm $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_vi.qm
	$(QINSTALL) /home/shenmo/Desktop/gxde-introduction/translations/dde-introduction_zh_CN.qm $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_zh_CN.qm
	$(QINSTALL) /home/shenmo/Desktop/gxde-introduction/translations/dde-introduction_zh_HK.qm $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_zh_HK.qm
	$(QINSTALL) /home/shenmo/Desktop/gxde-introduction/translations/dde-introduction_zh_TW.qm $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_zh_TW.qm

uninstall_qm_files: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_zh_TW.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_zh_HK.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_zh_CN.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_vi.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_uk.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_ug.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_tr.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_ta.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_sw.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_sv.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_sr.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_sq.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_sl.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_sk.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_ru.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_ro.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_pt_BR.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_pt.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_pl.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_pa.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_nl.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_ne.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_nb.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_ms.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_mn.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_ml.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_lt.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_lo.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_ku_IQ.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_ko.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_kn_IN.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_ja.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_it.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_id.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_hy.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_hu.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_hr.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_hi_IN.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_he.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_gl_ES.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_gl.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_fr.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_fil.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_fi.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_fa.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_es_419.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_es.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_eo.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_en_GB.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_en_AU.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_el.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_de.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_da.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_cs.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_ca.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_bn.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_bg.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_az.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_ast.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_ar.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_am_ET.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction_af.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/dde-introduction/translations/dde-introduction.qm
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/dde-introduction/translations/ 


install: install_desktop install_target install_icon install_qm_files  FORCE

uninstall: uninstall_desktop uninstall_target uninstall_icon uninstall_qm_files  FORCE

FORCE:

